<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        DB::table('clients')->insert([
            ['name' => '006 - ROLL - BOW COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '036 - CLINIDERM ROBERTO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '059 - CONSULT SOLUCOES EMPRESARIAIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '076 - CSE COMUNICAÇÃO INTERNA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '079 - RICARDO NONATO DA SILVA CHAVEIRO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '091 - ANGELIKA MARQUES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '095 - CEGI COMERCIO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '101 - ALVES ARAUJO SOCIEDADE', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '104 - GRUNOX EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '106 - J DEB EQUIPAMENTOS INOXIDAVEIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '119 - BELA EQUIPE', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '125 - SEGMAX COMERCIO E EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '133 - MAVARO INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '134 - MAVARO INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '135 - MIXSEG COMERCIO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '142 - EKO OFFICE EMPREENDIMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '143 - THATTO COMUNICACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '146 - PIRES ADMINISTRADORA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '151 - GV CENTER COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '159 - PONTO GARDEN', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '168 - QUINTAL DA VILLA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '170 - CPX COMERCIO E SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '174 - QUINTAL DA VILLA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '175 - QUINTAL DA VILLA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '180 - ARUJA-TINTAS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '181 - SOMHAR EQUIPAMENTOS DE SEGURANCA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '182 - MUNDO LINHA VIVA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '185 - MUNDO ENERGIA E EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '186 - L D FURTADO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '196 - DEL FIORI PROCESSAMENTO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '197 - GUTOMAQ INTERMEDIACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '198 - MAX COMERCIO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '199 - G5 BUSINESS EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '202 - THATTOCOM MARKETING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '203 - ART STEELX DECORACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '204 - HIRAMAQ-PECAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '205 - HIRAMAQ HOLDING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '208 - PIRES LOGISTICA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '209 - P PAN PRODUTOS PARA PANIFICACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '228 - GRUPO ZION SOLUCOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '229 - ZION TELECOM REPRESENTACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '223 - ARUJA-TINTAS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '234 - ARUJA-TINTAS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '245 - SECURITY COMERCIO E EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '248 - IQL - INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '251 - IDEA COATINGS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '252 - AOZAWA CONSULTORIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '253 - ANDERSON APARECIDO OZAWA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '254 - MOVEIS E TAPECARIA FANAN', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '255 - DELINEAR MOVEIS E DECORACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '256 - FORMA COMERCIO DE MOVEIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '257 - SOFIA COMERCIO DE MOVEIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '259 - OXIPAR SERVICOS E LOCACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '260 - ELECTRA SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '261 - OXIGENIO DO BRASIL CONSTRUCAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '262 - ALVES & TOLEDO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '265 - MAX COMERCIO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '268 - L & M HOLDING PATRIMONIAL', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '270 - CASA BLACK COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '271 - POUSADA TOKYO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '273 - UNIVERSO EQUIPAMENTOS DE SEGURANCA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '275 - W SERVICE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '276 - W SERVICE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '277 - W - POWER MANUTENCAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '278 - BEE DESENVOLVIMENTO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '282 - NEIMAR SERVICOS ADMINISTRATIVOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '284 - INDUSTRIA GRAFICA SÃO MATHEUS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '288 - RCS GRAFICA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '292 - UNIAO TOYS FESTAS FABRICACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '295 - CALEGARI SERVIÇOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '302 - W SUPPLY HOLDING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '304 - ELP HOLDING PATRIMONIAL', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '306 - COOPERATIVA AGRICOLA FLORES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '307 - KAMIMURA SHOPPING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '308 - KAMIMURA MATERIAL ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '311 - RJ EMPREENDIMENTOS IMOBILIARIOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '313 - TATIANA RAMOS GONCALVES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '314 - EUDES GONCALVES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '325 - OLIVIA MOVEIS E DECORACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '327 - M.G. GRACAS EMPREENDIMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '330 - MULTIVERSO LINHA VIVA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '331 - PLANETA EQUIPAMENTOS DE SEGURANCA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '332 - MM SERVICOS ADMINISTRATIVOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '333 - CLASSIC MÓVEIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '334 - KLAINTEC TECNOLOGIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '335 - KSOLUTION APOIO ADMINISTRATIVO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '336 - KLAINTELL SISTEMA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '337 - KLAINTEC SUPORTE', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '338 - ATMOSFERA ENERGIA ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '355 - JC INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '359 - A Z SERVIÇOS ADMINISTRATIVOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '367 - THUNDER TOOLS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '369 - MJG INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '370 - MINI TOYS HOLDING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '372 - A V CALEGARI DISTRIBUIDORA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '373 - LS CALEGARI COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '375 - PONTO S - SERVICOS TERCEIRIZADOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '376 - PRACTICE SEGURANCA E VIGILANCIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '399 - KLAINTEC SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '402 - POTENCIA ATACADISTA E VAREJISTA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '404 - GLOBALTECH TELECOMUNICACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '407 - ESTRE CORRETORA DE SEGUROS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '408 - BURANO CORRETORA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '409 - ABSOLUTA CONSTRUTORA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '410 - PERSIANAS EXPRESS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '411 - REDE CASA NOBRE SUZANO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '412 - B2CWHATS DESENVOLVIMENTO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '413 - NEOSIDE CONSULTORIA E SOLUCOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '414 - VOXEL TELECOMUNICACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '415 - JRS COMERCIO DE BRINQUEDOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '416- PET SHOP RENATA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '417 - PET SHOP RENATA ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '418 - PET SHOP RENATA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '422 - CONECTA CIDADANIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '424  ESCOLA DE AVIACAO CIVIL CIA DAS ASAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '426 - JOS MAO DE OBRA ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '427 - L. RAMOS CRUZ EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '428 - EXITUM SERVICO DE APOIO ADMINISTRATIVO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '429 - WORTH LOCACAO DE MAQUINAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '436 - ABMOBI INTERMEDIACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '437 - 2SS HOLDING ADMINISTRACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '439 - M. P. COMERCIO DE MOVEIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '440 - K-LOG LOCACAO DE VEICULOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '443 - EGONCALVES TRANSPORTES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '444 - ALVES ARAUJO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => "453 - SCHUELER'S HOLDING ADMINISTRACAO", 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '454- ELECTRA SERVICOS ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '455 - J LOC LOCACAO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '456 - ALR SANTOS FESTA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '457 - ENGECON MANUTENCAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '458 - AMPVOLTS SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '459 - 3G MANUTENCAO ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '460 - MIXSEG COMERCIO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '462 - ARUJA-TINTAS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '463 - BR45 PARTICIPACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '465 - SPEED GRAFICA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '466 - SRS GRAFICA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '467 - FSF FESTA COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '468 - JOMALU COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '469 - R & R TOZATTI HOLDING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '477 - TOP 10 COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '478 - CVA COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '479 - CML COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '480 - RJG GRAFICA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '482 - CIA DAS RACOES COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '485 - HC COMERCIO E SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '486 - GLOBALTECH TELECOMUNICAÇÕES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '487 - PRESLEY INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '488 - ELVIS HOLDING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '489 - AMORELOS CONFECCAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '491 - STR EMPREENDIMENTOS IMOBILIARIOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '500 - IMPULSO PET COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '501 - PYRAMID INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '502 - DIX INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '503 - MELKOR SERVICE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '504 - OSKA PARTICIPAÇÕES E EMPREENDIMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '505 - TOP CINTOS INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '507 - ARAUJO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '509 - ARTIFEST INDUSTRIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '511 - MAXIFORCE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '512 - SMART LOCACOES COMERCIAIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '513 - VISÃO FEST  COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '514- A. ARAUJO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '515 - FAST FLORES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '516 - SERGIO HIDEYOSHI NAKAMURA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '517 - KIFESTAS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '518 - MARCELO HENRIQUE NOGUEIRA PORTO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '519 - TUFF COMERCIO DE CONFECCOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '520 - H & H TRANSPORTES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '521 - H N H TRANSPORTES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '522 - CIDASI MATERIAIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '523 - CALEO INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '524 - PET 2 W ARTIGOS PARA PET', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '527 - KM EMPREENDIMENTOS IMOBILIARIOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '528 - SITIO CAMPO DAS FLORES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '529 - AZEVEDO INDUSTRIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '530 - QUASE TUDO INDUSTRIA DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '531 - LUZI INDUSTRIA DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '532 - VIEIRA ARAUJO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '533 - EVOLEAN SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '535 - VERA LUCIA FIRMINO JUNQUEIRA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '536 - VERA LUCIA FIRMINO JUNQUEIRA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '537 - VERA LUCIA FIRMINO JUNQUEIRA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '538 - W SERVICE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '539 - GREEN PLUGS PRODUCAO ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '540 - SITIO GREEN PLUGS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '541 - RAI COMERCIO DE ARTIGOS DE FESTA ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '542 - J COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '543 - V COMERCIO DE ARTIGOS DE FESTAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '544 - L MONTEIRO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '546 - PET TOYS DISTRIBUICAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '547 - LU COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '548 - TAZ COMERCIO DE ARTIGOS DE FESTAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '549 - GENU COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '550 - LSC COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '551 - MUNDO FIBRA COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '553 - AMIPET CARE SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '554 - DB4 PET CENTER', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '555 - AMIPET CARE SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '556 - PET SHOP B&B', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '557 - CONDOR PET CENTER', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '558 - PET CENTER SUZANO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '559 - R CANCIO COMERCIO DE ARTIGOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '560 - SOUZA COMÉRCIO E INDUSTRIA DE BRINQUEDOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '562 - PET SHOP RENATA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '563 - PET SHOP RENATA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '564 - PET SHOP RENATA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '565 - PYRAMID INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '566 - MAXIFORCE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '567 - VOVO BEL INDUSTRIA DE ALIMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '568 - CASA DO QUEIJO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '569 - E2G DESIGN COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '570 - IN HOUSE COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '571 - IDEAL EXPRESS TRANSPORTES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '572 - AGENCIA IDEAL', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '573 - IDEAL EXPRESS TRANSPORTES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '574 - ART STEEL DESIGN', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '580 - UNIAO TOYS FESTAS FABRICACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '581 - CALEO INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '582 - ALUMISTOCK COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '583 - SUPERMANUTENCAO MATERIAIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '584 - S.R. DA SILVA - COMERCIO EM GERAL', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '585 - RDV TRANSPORTES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '586 - ANIMARIUM COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '587 - YOU TECNOLOGIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '588 - VOVO BEL COMERCIO E LANCHONETE', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '589 - KLJ HOLDING PATRIMONIAL', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '590 - F.A.M.A HOLDING ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '592 - NORI PET SHOP', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '594 - RAFRE SERVICOS TERCEIRIZADOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '595 - RP SERVICOS TERCEIRIZADOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '596- RAFAZ SERVICOS TERCEIRIZADOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '598 - VERTIQ INVESTIMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '599 - VERTIQ AGENTES AUTONOMOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '600 - L D FURTADO COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '601 - REDE CN COMERCIO DE MOVEIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '602 - IGNIS SECURITY EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '603 - IGNIS LTDA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '604 - IGNIS FIRE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '605 - HI CONTROL SISTEMAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '606- CIA DAS RACOES COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '607 - J. GIANINI SERVICOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '608 - KG SOLUCOES EM ESQUADRIAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '609 - GIALUM - GIANINI ESQUADRIAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '610 - J GIANINI ESQUADRIAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '611 - GQUATRO SOLUCOES EM ESQUADRIAS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '613 - VALDAR MONTAGENS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '614 - CRYSTAL INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '615 - ELECTRA LOCACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '616 - W SUPPLY MANUTENCAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '618 - MAX COMERCIO DE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '619- LOTTO EQUIPAMENTOS DE SEGURANCA ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '620 - C.A AMARAL REPRESENTACOES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '621 - NF PET - INDUSTRIA , COMERCIO E DISTRIBUICAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '622 - NOSSOS FILHOS PET INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '623 - DOMOS COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '624 - TP BIKERS INDUSTRIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '625 - TP MOTORS - INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '627 - PERFORMANCE EQUIPAMENTOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '628 - RODRIGO DE CASTRO NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '629 - RODRIGO DE CASTRO NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '630 - LARISSA BATISTA NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '631 - RODRIGO DE CASTRO NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '632 - LARISSA BATISTA NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '633 - MARIA IOLITA DE CASTRO NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '634 - MARIA IOLITA DE CASTRO NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '635 - MARIA IOLITA DE CASTRO NOVAES', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '636 - REDE RCN HOLDING', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '637 - MARCENARIA UNIS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '638 - RIBEIRO INDUSTRIALIZACAO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '639 - IVAMAR INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '640 - MARIO VIEIRA INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '641 - CARDOSO INDUSTRIA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '642 - N.M. INDUSTRIA E COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '643 - J C LOG LTDA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '644 - VILA OLIMPIA COMERCIO', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '645 - STYLLO MONTAGENS E INSTALACOES ', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '646 - ALFA NET DISTRIBUIDORA', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '647 - CKP SERVICOS ADMINISTRATIVOS', 'disponibility' => '1', 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}
